In [9]:
import numpy as np
import scipy.io
import matplotlib.pyplot as plt

chi2_file = np.load('../data/chi2_1000000_allmodes.npz')
chi2_array = chi2_file['chi2']

# load IAM
f = np.load('../data/iam_arrays_1000000_allmodes.npz')
q = f['q']
pcd = f['pcd']

# load experiment data
datafile = '../data/NMM_exp_dataset.mat'
mat = scipy.io.loadmat(datafile)
q_exp = np.squeeze(mat['q'])
t_exp = np.squeeze(mat['t'])
pcd_exp = mat['iso']
errors = mat['iso_stdx']
i_pre_t0 = 13
t_exp = t_exp[i_pre_t0:]  # remove before t = 0
pcd_exp = pcd_exp[:, i_pre_t0:]
errors = errors[:, i_pre_t0:]

print(t_exp)
print(len(t_exp))

# indices of 10 lowest values
time_step = 50
k = 5
idx = np.argpartition(np.squeeze(chi2_array[:, time_step]), k)
print(idx[:k])

# load xyz array
xyz_file = np.load('../data/xyz_array_1000000_allmodes.npz')
xyz = xyz_file['xyz']

print(xyz[:,:,0])

[-0.35 -0.3  -0.25 -0.2  -0.15 -0.1  -0.05  0.    0.05  0.1   0.15  0.2
  0.25  0.3   0.35  0.4   0.45  0.5   0.55  0.6   0.65  0.7   0.75  0.8
  0.85  0.9   0.95  1.    1.05  1.1   1.15  1.2   1.25  1.3   1.35  1.4
  1.45  1.5   1.55  1.6   1.65  1.7   1.75  1.8   1.85  1.9   1.95  2.
  2.05  2.1   2.15  2.2   2.25  2.3   2.35  2.4   2.45  2.5   2.55  2.6
  2.65  2.7   2.75  2.8   2.85  2.9   2.95  3.    3.05  3.1   3.15  3.2
  3.25  3.3   3.35  3.4   3.45  3.5   3.55  3.6   3.75  3.8   3.85  3.9
  3.95  4.  ]
86
[488887 692061 199351 918371 949575]
[[ 1.28644010e+00 -2.69272741e-01 -1.11102004e+00]
 [ 1.14236997e+00  7.03590500e-01  2.67587802e-01]
 [ 2.27523597e+00  6.69515654e-01  1.00618356e+00]
 [-5.36839464e-02 -7.93575920e-02  9.18148523e-01]
 [ 1.14429741e+00  1.92007103e+00  2.27628086e-01]
 [-1.19723574e+00  7.62672081e-01  2.31257752e-01]
 [ 3.04300419e-02 -5.87303601e-01  2.47806644e+00]
 [ 6.38249885e-04  2.53051616e-01  3.40094723e+00]
 [ 9.36658278e-01 -1.66989908e+00  

### 